apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-credentials
  namespace: databases
$patch: delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-postgres
  namespace: n8n
$patch: delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-app
  namespace: n8n
$patch: delete
